POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "username": "John",
    "email": "blablabla@gmail.com",
    "password": "senha123"
}

###

POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "blablabla@gmail.com",
  "password": "senha123"
}

###
